import argparse
import os

import torch
import numpy as np  # noqa: F401  # kept for backward-compat if used in configs

from diffusers import StableDiffusion3Pipeline, FluxPipeline, AuraFlowPipeline
from diffusers import StochasticRFOvershotDiscreteScheduler

from utils.prompt_parser import parse_prompt
from utils.text_renderer import render_text_to_image, TextRenderConfig
from utils.image_composer import overlay_text_on_scene


def log(msg: str) -> None:
    """Simple, safe logger for CLI usage."""
    try:
        print(msg)
    except Exception:
        pass


def build_pipeline(model_type: str):
    """Create and return the diffusion pipeline + default guidance scale."""
    if model_type == "sd3":
        pipe = StableDiffusion3Pipeline.from_pretrained(
            "stabilityai/stable-diffusion-3-medium-diffusers",
            torch_dtype=torch.float32,
        )
        guidance_scale = 7.0
    elif model_type == "flux":
        pipe = FluxPipeline.from_pretrained(
            "black-forest-labs/FLUX.1-dev",
            torch_dtype=torch.bfloat16,
        )
        guidance_scale = 3.5
    elif model_type == "auraflow":
        pipe = AuraFlowPipeline.from_pretrained(
            "fal/AuraFlow",
            torch_dtype=torch.float16,
        )
        guidance_scale = 3.5
    else:
        raise ValueError(f"Unsupported model_type: {model_type}")

    pipe.enable_model_cpu_offload()
    return pipe, guidance_scale


def configure_scheduler(pipe, scheduler: str, c: float, use_att: bool) -> str:
    """Configure scheduler (same logic as original run.py) and return exp_prefix."""
    if scheduler == "overshoot":
        scheduler_config = pipe.scheduler.config
        scheduler_obj = StochasticRFOvershotDiscreteScheduler.from_config(scheduler_config)
        overshot_func = lambda t, dt: t + dt
        exp_prefix = f"{scheduler}_c={str(c).zfill(4)}_use_att={use_att}"

        pipe.scheduler = scheduler_obj
        pipe.scheduler.set_c(c)
        pipe.scheduler.set_overshot_func(overshot_func)
    elif scheduler == "euler":
        exp_prefix = f"{scheduler}"
    else:
        raise ValueError(f"Unknown scheduler: {scheduler}")

    return exp_prefix


def run(args) -> None:
    """
    Main entry for image generation with deterministic text rendering.

    - Scene generation: unchanged AMO behaviour (Flux / SD3 / AuraFlow).
    - Text: NEVER generated by the model; instead:
        * We extract quoted text from the prompt.
        * We generate the scene from the cleaned prompt (no quoted text).
        * We render the text using Pillow (Arabic or English).
        * We overlay the rendered text onto the scene image.
    """
    # 0) Read prompts
    with open(args.prompt_file, "r", encoding="utf-8") as file:
        prompts = [line.rstrip("\n") for line in file]

    # 1) Build pipeline
    pipe, guidance_scale = build_pipeline(args.model_type)

    # 2) Configure scheduler
    exp_prefix = configure_scheduler(pipe, args.scheduler, args.c, args.use_att)

    # 3) Generate images per prompt
    for i, raw_prompt in enumerate(prompts):
        raw_prompt = raw_prompt.strip()

        file_save_dir = os.path.join(
            args.exp_dir,
            "generated_image",
            f"num_steps={str(args.num_inference_steps).zfill(4)}",
            exp_prefix,
        )
        os.makedirs(file_save_dir, exist_ok=True)
        img_save_path = os.path.join(file_save_dir, f"sample_{str(i).zfill(4)}.png")

        generator = torch.Generator(device="cuda" if torch.cuda.is_available() else "cpu")
        generator.manual_seed(args.seed)

        # --- Prompt parsing: extract quoted text ---
        parsed = parse_prompt(raw_prompt)
        clean_prompt = parsed.clean_prompt or raw_prompt

        if parsed.text:
            lang = parsed.language or "en"
            log(f"[INFO] Detected quoted text (language={lang}): {parsed.text}")
            log(f"[INFO] Clean prompt for scene generation: {clean_prompt}")
        else:
            log("[INFO] No quoted text detected; using full prompt for scene generation.")
            log(f"[INFO] Prompt: {clean_prompt}")

        # --- Scene generation (unchanged behaviour) ---
        output = pipe(
            prompt=clean_prompt,
            num_inference_steps=args.num_inference_steps,
            height=args.img_size,
            width=args.img_size,
            guidance_scale=guidance_scale,
            generator=generator,
            use_att=args.use_att,
        )
        scene_image = output.images[0]

        # --- Deterministic text rendering and composition ---
        if parsed.text:
            try:
                # Configure text rendering; scale reasonably with image size.
                render_cfg = TextRenderConfig(
                    font_size=min(96, args.img_size // 10),
                    color=(0, 0, 0, 255),
                    padding=max(8, args.img_size // 64),
                    max_width=int(args.img_size * 0.8),
                )

                text_img = render_text_to_image(parsed.text, parsed.language or "en", render_cfg)
                log("[INFO] Rendering text using deterministic renderer (Pillow)")

                composed = overlay_text_on_scene(
                    scene_image,
                    text_img,
                    position="center",
                    y_offset_fraction=0.2,  # push slightly upwards (billboard-like)
                )
                composed.save(img_save_path)
                log(f"[INFO] Final image with text saved at: {img_save_path}")
            except Exception as exc:
                # Never break main pipeline due to text errors.
                log(f"[WARN] Text rendering/composition failed; saving scene only. Error: {exc}")
                scene_image.save(img_save_path)
        else:
            # No text in prompt; save pure scene.
            scene_image.save(img_save_path)
            log(f"[INFO] Scene image saved at: {img_save_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--scheduler",
        type=str,
        default="euler",
        help="scheduler to use",
    )
    parser.add_argument(
        "--c",
        type=float,
        default=2.0,
        help="c value for overshooting scheduler",
    )
    parser.add_argument(
        "--prompt_file",
        type=str,
        default="prompts.txt",
        help="file with prompts",
    )
    parser.add_argument(
        "--num_inference_steps",
        type=int,
        default=28,
        help="number of steps",
    )
    parser.add_argument(
        "--exp_dir",
        type=str,
        default="exps/flux",
        help="experiment directory",
    )
    parser.add_argument(
        "--model_type",
        type=str,
        default="flux",
        choices=["sd3", "flux", "auraflow"],
        help="model type",
    )
    parser.add_argument(
        "--use_att",
        action="store_true",
        help="use attention",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=10,
        help="seed",
    )
    parser.add_argument(
        "--img_size",
        type=int,
        default=1024,
        help="image size",
    )
    args = parser.parse_args()

    run(args)

import argparse
import os
from typing import Optional

import torch
import numpy as np

from diffusers import StableDiffusion3Pipeline, FluxPipeline, AuraFlowPipeline
from diffusers import StochasticRFOvershotDiscreteScheduler

from utils.prompt_parser import parse_prompt
from utils.text_renderer import render_text_to_image, TextRenderConfig
from utils.image_composer import overlay_text_on_scene


def log(msg: str) -> None:
    """Simple, safe logger."""
    try:
        print(msg)
    except Exception:
        pass


def run(args) -> None:
    """
    Main entry point for image generation.

    Scene generation:
        - Uses existing AMO pipeline (Flux / SD3 / AuraFlow).
        - Uses ONLY the cleaned prompt (without quoted text).

    Text rendering:
        - Extracts quoted text from the prompt.
        - Renders text deterministically with Pillow (Arabic or English).
        - Overlays rendered text onto the generated scene.
    """
    with open(args.prompt_file, "r", encoding="utf-8") as file:
        prompts = file.readlines()

    # --- Pipeline selection (unchanged scene generation logic) ---
    if args.model_type == "sd3":
        pipe = StableDiffusion3Pipeline.from_pretrained(
            "stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float32
        )
        guidance_scale = 7.0
    elif args.model_type == "flux":
        pipe = FluxPipeline.from_pretrained(
            "black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
        )
        guidance_scale = 3.5
    elif args.model_type == "auraflow":
        pipe = AuraFlowPipeline.from_pretrained(
            "fal/AuraFlow", torch_dtype=torch.float16
        )
        guidance_scale = 3.5
    else:
        raise ValueError(f"Unsupported model_type: {args.model_type}")

    pipe.enable_model_cpu_offload()

    # --- Scheduler selection (unchanged) ---
    if args.scheduler == "overshoot":
        scheduler_config = pipe.scheduler.config
        scheduler = StochasticRFOvershotDiscreteScheduler.from_config(scheduler_config)
        overshot_func = lambda t, dt: t + dt
        exp_prefix = f"{args.scheduler}_c={str(args.c).zfill(4)}_use_att={args.use_att}"

        pipe.scheduler = scheduler
        pipe.scheduler.set_c(args.c)
        pipe.scheduler.set_overshot_func(overshot_func)
    elif args.scheduler == "euler":
        exp_prefix = f"{args.scheduler}"
    else:
        raise ValueError(f"Unknown scheduler: {args.scheduler}")

    # --- Per-prompt generation ---
    for i, raw_prompt_line in enumerate(prompts):
        raw_prompt = raw_prompt_line.strip()

        file_save_dir = os.path.join(
            args.exp_dir,
            "generated_image",
            f"num_steps={str(args.num_inference_steps).zfill(4)}",
            exp_prefix,
        )
        os.makedirs(file_save_dir, exist_ok=True)
        img_save_path = os.path.join(file_save_dir, f"sample_{str(i).zfill(4)}.png")

        generator = torch.Generator(device="cuda" if torch.cuda.is_available() else "cpu")
        generator.manual_seed(args.seed)

        # 1) Parse prompt: separate scene description and text.
        parsed = parse_prompt(raw_prompt)
        clean_prompt = parsed.clean_prompt or raw_prompt

        if parsed.text:
            lang = parsed.language or "en"
            log(f"[INFO] Text detected in prompt (language={lang}): {parsed.text}")
            log(f"[INFO] Clean prompt for diffusion: {clean_prompt}")
        else:
            log("[INFO] No quoted text detected; using full prompt for diffusion.")
            log(f"[INFO] Prompt: {clean_prompt}")

        # 2) Generate scene image using ONLY the clean prompt.
        output = pipe(
            prompt=clean_prompt,
            num_inference_steps=args.num_inference_steps,
            height=args.img_size,
            width=args.img_size,
            guidance_scale=guidance_scale,
            generator=generator,
            use_att=args.use_att,
        )
        scene_image = output.images[0]

        # 3) Deterministically render and overlay text, if any.
        if parsed.text:
            try:
                render_cfg = TextRenderConfig(
                    font_size=min(96, args.img_size // 12),
                    color=(0, 0, 0, 255),
                    padding=max(8, args.img_size // 64),
                    max_width=int(args.img_size * 0.8),
                )
                text_img = render_text_to_image(parsed.text, parsed.language or "en", render_cfg)
                log("[INFO] Rendering text using deterministic renderer")

                composed = overlay_text_on_scene(
                    scene_image,
                    text_img,
                    position="center",
                    y_offset_fraction=0.2,  # Slightly above vertical centre (billboard-like)
                )
                composed.save(img_save_path)
                log(f"[INFO] Final image with text saved at: {img_save_path}")
            except Exception as exc:
                log(f"[WARN] Text rendering/composition failed, saving scene only. Error: {exc}")
                scene_image.save(img_save_path)
        else:
            # No text to overlay; save scene as-is.
            scene_image.save(img_save_path)
            log(f"[INFO] Scene image saved at: {img_save_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--scheduler",
        type=str,
        default="euler",
        help="scheduler to use",
    )
    parser.add_argument(
        "--c",
        type=float,
        default=2.0,
        help="c value for overshooting scheduler",
    )
    parser.add_argument(
        "--prompt_file",
        type=str,
        default="prompts.txt",
        help="file with prompts",
    )
    parser.add_argument(
        "--num_inference_steps",
        type=int,
        default=28,
        help="number of steps",
    )
    parser.add_argument(
        "--exp_dir",
        type=str,
        default="exps/flux",
        help="experiment directory",
    )
    parser.add_argument(
        "--model_type",
        type=str,
        default="flux",
        choices=["sd3", "flux", "auraflow"],
        help="model type",
    )
    parser.add_argument(
        "--use_att",
        action="store_true",
        help="use attention",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=10,
        help="seed",
    )
    parser.add_argument(
        "--img_size",
        type=int,
        default=1024,
        help="image size",
    )
    args = parser.parse_args()

    run(args)

import argparse
import os
import torch
import numpy as np

from diffusers import StableDiffusion3Pipeline, FluxPipeline, AuraFlowPipeline
from diffusers import StochasticRFOvershotDiscreteScheduler

from arabic_text_utils import (
    contains_arabic,
    extract_arabic_text,
    prepare_arabic_for_rendering,
    build_arabic_output_path,
    log as arabic_log,
)

# Phase-1 Arabic ControlNet rendering (runs after existing Arabic post-processing)
try:
    from arabic_controlnet import ArabicControlNetRenderer, create_control_image_from_text
    from arabic_ocr_validator import ArabicOCRValidator
    PHASE1_ARABIC_AVAILABLE = True
except ImportError:
    PHASE1_ARABIC_AVAILABLE = False


def _maybe_generate_arabic_only_image(
    pipe,
    original_prompt: str,
    guidance_scale: float,
    num_inference_steps: int,
    img_size: int,
    generator: torch.Generator,
    use_att: bool,
    original_img_path: str,
) -> None:
    """
    Optional post-processing step for prompts containing Arabic text.

    This runs strictly AFTER the original image is generated and saved, and it:
    - Detects Arabic in the prompt using Unicode ranges.
    - Extracts the exact Arabic text (no translation, no rewriting).
    - Prepares the text for visual rendering (reshaping + bidi).
    - Generates a second image focused solely on rendering that Arabic text.

    The original diffusion call and output path remain unchanged.
    """
    try:
        if not contains_arabic(original_prompt):
            return

        arabic_log(print, "Detected Arabic text in prompt, preparing Arabic-only image...")

        extracted = extract_arabic_text(original_prompt)
        if not extracted:
            arabic_log(print, "Arabic detection found script, but no stable substring to extract.")
            return

        arabic_log(print, f"Detected Arabic text: {extracted}")
        arabic_log(print, f"Extracted text (repr): {repr(extracted)}")
        arabic_log(print, f"Extracted text (hex): {extracted.encode('utf-8').hex()}")

        prepared_text = prepare_arabic_for_rendering(extracted)
        arabic_log(print, f"Prepared Arabic text: {prepared_text}")
        arabic_log(print, f"Prepared text (repr): {repr(prepared_text)}")

        # WORKAROUND: Create a reference image showing what text was extracted
        # This helps verify that extraction is working correctly
        try:
            from arabic_dataset import ArabicDatasetGenerator
            temp_generator = ArabicDatasetGenerator(image_size=(img_size, img_size))
            reference_image = temp_generator.generate_image(
                extracted,
                font_size=min(128, img_size // 8),
                text_color=(0, 0, 0),
                bg_color=(255, 255, 255),
            )
            # Save reference image for verification
            ref_img_path = original_img_path.replace(".png", "_reference_arabic.png")
            reference_image.save(ref_img_path)
            arabic_log(print, f"Saved reference image showing extracted text: {ref_img_path}")
            arabic_log(print, "Created reference image with rendered Arabic text")
        except Exception as ref_exc:
            arabic_log(print, f"Could not create reference image: {ref_exc}")
            reference_image = None

        # Build a controlled prompt that explicitly asks for clean Arabic text.
        # IMPORTANT: The diffusion model's text encoder doesn't understand Arabic,
        # so it will hallucinate Arabic words. This is why we need Phase-1 ControlNet.
        # The model may generate random Arabic words like "خَمْرَة" (wine) instead of the actual text.
        arabic_prompt = (
            "A clean image that displays the exact Arabic text: "
            f"{prepared_text}, rendered clearly, legibly, centered, "
            "with no distortion and no extra characters."
        )

        arabic_log(print, f"Full prompt being sent to model: {arabic_prompt}")
        arabic_log(print, f"Prompt length: {len(arabic_prompt)} characters")
        arabic_log(print, "WARNING: Model may hallucinate Arabic text - this is expected without Phase-1 ControlNet")
        arabic_log(print, "Generating Arabic-only image")

        # Use a different seed for Arabic generation to avoid same-word bias
        import random
        arabic_seed = generator.initial_seed() + 1000 if hasattr(generator, 'initial_seed') else random.randint(1000, 9999)
        arabic_generator = torch.Generator(device=generator.device if hasattr(generator, 'device') else 'cuda')
        arabic_generator.manual_seed(arabic_seed)
        arabic_log(print, f"Using seed {arabic_seed} for Arabic generation (original seed + 1000)")

        output = pipe(
            prompt=arabic_prompt,
            num_inference_steps=num_inference_steps,
            height=img_size,
            width=img_size,
            guidance_scale=guidance_scale,
            generator=arabic_generator,
            use_att=use_att,
        )

        arabic_image = output.images[0]
        arabic_img_path = build_arabic_output_path(original_img_path)
        arabic_image.save(arabic_img_path)

        arabic_log(print, f"Saved Arabic image to {arabic_img_path}")
        
        # Phase-1 Arabic ControlNet rendering (runs after existing Arabic post-processing)
        # This uses a trained ControlNet to generate more accurate Arabic text rendering
        _maybe_render_with_phase1_controlnet(
            extracted_arabic=extracted,
            prepared_text=prepared_text,
            original_img_path=arabic_img_path,  # Use the Arabic image path, not original
            guidance_scale=guidance_scale,
            num_inference_steps=num_inference_steps,
            img_size=img_size,
            generator=generator,
        )

    except Exception as exc:
        # Any failure in Arabic-specific logic must NEVER break the main pipeline.
        arabic_log(print, f"Arabic post-processing failed, skipping Arabic-only image. Error: {exc}")


def _maybe_render_with_phase1_controlnet(
    extracted_arabic: str,
    prepared_text: str,
    original_img_path: str,
    guidance_scale: float,
    num_inference_steps: int,
    img_size: int,
    generator: torch.Generator,
) -> None:
    """
    Phase-1 Arabic ControlNet rendering (optional, runs after existing Arabic post-processing).
    
    This function:
    - Checks if Phase-1 Arabic ControlNet is available and trained
    - Creates a control image from the Arabic text
    - Uses ControlNet to generate a more accurate Arabic text image
    - Validates output with OCR
    - Saves validated image
    
    This is a NEW capability that runs AFTER the existing Arabic post-processing,
    so existing functionality is never affected.
    """
    if not PHASE1_ARABIC_AVAILABLE:
        return  # Phase-1 not available, skip silently
    
    try:
        # Check if ControlNet model exists
        controlnet_path = os.getenv("ARABIC_CONTROLNET_PATH", "arabic_controlnet_checkpoint")
        if not os.path.exists(controlnet_path):
            # ControlNet not trained yet, skip Phase-1 rendering
            return
        
        arabic_log(print, "Phase-1 Arabic ControlNet detected, generating enhanced Arabic image...")
        
        # Initialize renderer (lazy load to avoid breaking if dependencies missing)
        renderer = ArabicControlNetRenderer(
            controlnet_path=controlnet_path,
            device="cuda" if torch.cuda.is_available() else "cpu",
        )
        
        # Create control image from Arabic text
        control_image = create_control_image_from_text(
            prepared_text,
            image_size=(img_size, img_size),
            font_size=min(64, img_size // 8),
        )
        
        # Generate image with ControlNet
        arabic_log(print, "Generating Phase-1 Arabic image with ControlNet...")
        phase1_image = renderer.render(
            arabic_text=extracted_arabic,
            control_image=control_image,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator,
        )
        
        # Validate with OCR
        arabic_log(print, "Validating Phase-1 Arabic image with OCR...")
        validator = ArabicOCRValidator()
        is_valid, extracted_text, similarity = validator.validate(
            phase1_image,
            extracted_arabic,
            tolerance=0.9,
        )
        
        if is_valid:
            # Save validated image
            phase1_path = original_img_path.replace(".png", "_phase1_arabic.png")
            phase1_image.save(phase1_path)
            arabic_log(print, f"Phase-1 Arabic image validated (similarity: {similarity:.2f}) and saved to {phase1_path}")
        else:
            arabic_log(print, f"Phase-1 Arabic image failed OCR validation (similarity: {similarity:.2f}, extracted: {extracted_text})")
            # Optionally save anyway for debugging
            phase1_path = original_img_path.replace(".png", "_phase1_arabic_rejected.png")
            phase1_image.save(phase1_path)
            arabic_log(print, f"Rejected image saved to {phase1_path} for debugging")
    
    except Exception as exc:
        # Phase-1 failures must NEVER break the main pipeline
        arabic_log(print, f"Phase-1 Arabic ControlNet rendering failed, skipping. Error: {exc}")


def run(args):
    with open(args.prompt_file, 'r', encoding='utf-8') as file:
        prompts = file.readlines()
    
    if args.model_type == "sd3":
        pipe = StableDiffusion3Pipeline.from_pretrained(
            "stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float32
        )
        guidance_scale = 7.0
    elif args.model_type == "flux":
        pipe = FluxPipeline.from_pretrained(
            "black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
        )
        guidance_scale = 3.5
    elif args.model_type == "auraflow": 
        pipe = AuraFlowPipeline.from_pretrained(
            "fal/AuraFlow", torch_dtype=torch.float16
        )
        guidance_scale = 3.5
    pipe.enable_model_cpu_offload()
    
    if args.scheduler == 'overshoot':
        scheduler_config = pipe.scheduler.config
        scheduler = StochasticRFOvershotDiscreteScheduler.from_config(scheduler_config)
        overshot_func = lambda t, dt: t+dt
        exp_prefix = f"{args.scheduler}_c={str(args.c).zfill(4)}_use_att={args.use_att}"
        
        pipe.scheduler = scheduler
        pipe.scheduler.set_c(args.c)
        pipe.scheduler.set_overshot_func(overshot_func)
    elif args.scheduler == "euler":
        exp_prefix = f"{args.scheduler}"
    
    for i in range(len(prompts)):
        file_save_dir = os.path.join(
            args.exp_dir,
            "generated_image",
            f"num_steps={str(args.num_inference_steps).zfill(4)}",
            exp_prefix,
        )
        os.makedirs(file_save_dir, exist_ok=True)
        img_save_path = os.path.join(file_save_dir, f"sample_{str(i).zfill(4)}.png")
        
        generator = torch.Generator(device='cuda')
        generator.manual_seed(args.seed)
        
        prompt = prompts[i]
        output = pipe(
            prompt=prompt,
            num_inference_steps=args.num_inference_steps,
            height=args.img_size,
            width=args.img_size,
            guidance_scale=guidance_scale,
            generator=generator,
            use_att=args.use_att, 
        )
        image = output.images[0]
        image.save(img_save_path)

        # Arabic-specific post-processing: runs strictly after the original image is saved.
        _maybe_generate_arabic_only_image(
            pipe=pipe,
            original_prompt=prompt,
            guidance_scale=guidance_scale,
            num_inference_steps=args.num_inference_steps,
            img_size=args.img_size,
            generator=generator,
            use_att=args.use_att,
            original_img_path=img_save_path,
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--scheduler", type=str, default="euler", 
                        help="scheduler to use")
    parser.add_argument("--c", type=float, default=2.0, help="c value for overshooting scheduler")
    parser.add_argument("--prompt_file", type=str, default="prompts.txt", 
                        help="file with prompts")
    parser.add_argument("--num_inference_steps", type=int, default=28, 
                        help="number of steps")
    parser.add_argument("--exp_dir", type=str, default="exps/flux", 
                        help="experiment directory")
    parser.add_argument("--model_type", type=str, default="flux", 
                        choices=["sd3", "flux", "auraflow"], help="model type")
    parser.add_argument("--use_att", action="store_true", help="use attention")
    parser.add_argument("--seed", type=int, default=10, help="seed")
    parser.add_argument("--img_size", type=int, default=1024, help="image size")
    args = parser.parse_args()
    
    run(args)
    