"""
Phase-1 Arabic ControlNet Training Script.

This script trains a ControlNet model for accurate Arabic text rendering
using the synthetic dataset generated by arabic_dataset.py.

Usage:
    python train_arabic_phase1.py --vocabulary_file arabic_vocabulary.txt --output_dir arabic_controlnet_checkpoint
"""

import argparse
import os
from pathlib import Path

from arabic_dataset import generate_phase1_dataset, ArabicDatasetGenerator
from arabic_controlnet import train_arabic_controlnet


def load_vocabulary(vocabulary_file: str) -> list[str]:
    """
    Load Arabic vocabulary from file.
    
    Args:
        vocabulary_file: Path to text file with one Arabic word per line
        
    Returns:
        List of Arabic words
    """
    with open(vocabulary_file, "r", encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]
    return words


def main():
    parser = argparse.ArgumentParser(description="Train Phase-1 Arabic ControlNet")
    parser.add_argument(
        "--vocabulary_file",
        type=str,
        required=True,
        help="Text file with Arabic words (one per line)",
    )
    parser.add_argument(
        "--dataset_dir",
        type=str,
        default="arabic_dataset_phase1",
        help="Directory to save/load synthetic dataset",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="arabic_controlnet_checkpoint",
        help="Directory to save trained ControlNet",
    )
    parser.add_argument(
        "--base_model",
        type=str,
        default="runwayml/stable-diffusion-v1-5",
        help="Base Stable Diffusion model",
    )
    parser.add_argument(
        "--images_per_word",
        type=int,
        default=10,
        help="Number of image variations per word",
    )
    parser.add_argument(
        "--num_epochs",
        type=int,
        default=10,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=4,
        help="Training batch size",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=1e-5,
        help="Learning rate",
    )
    parser.add_argument(
        "--resolution",
        type=int,
        default=512,
        help="Image resolution",
    )
    parser.add_argument(
        "--skip_dataset_generation",
        action="store_true",
        help="Skip dataset generation if dataset already exists",
    )
    
    args = parser.parse_args()
    
    # Step 1: Load vocabulary
    print(f"Loading vocabulary from {args.vocabulary_file}...")
    vocabulary = load_vocabulary(args.vocabulary_file)
    print(f"Loaded {len(vocabulary)} Arabic words")
    
    if len(vocabulary) < 100:
        print("WARNING: Phase-1 recommends 100-500 words. Current vocabulary is small.")
    
    # Step 2: Generate synthetic dataset
    if not args.skip_dataset_generation or not os.path.exists(args.dataset_dir):
        print(f"Generating synthetic dataset in {args.dataset_dir}...")
        generate_phase1_dataset(
            vocabulary=vocabulary,
            output_dir=args.dataset_dir,
            images_per_word=args.images_per_word,
        )
        print("Dataset generation complete!")
    else:
        print(f"Using existing dataset in {args.dataset_dir}")
    
    # Step 3: Train ControlNet
    print(f"Starting ControlNet training...")
    print(f"This will train a ControlNet model for accurate Arabic text rendering.")
    print(f"Training parameters:")
    print(f"  - Epochs: {args.num_epochs}")
    print(f"  - Batch size: {args.batch_size}")
    print(f"  - Learning rate: {args.learning_rate}")
    print(f"  - Resolution: {args.resolution}")
    
    train_arabic_controlnet(
        dataset_dir=args.dataset_dir,
        output_dir=args.output_dir,
        base_model=args.base_model,
        num_train_epochs=args.num_epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        resolution=args.resolution,
    )
    
    print(f"Training complete! Model saved to {args.output_dir}")
    print(f"To use the trained model, set ARABIC_CONTROLNET_PATH environment variable:")
    print(f"  export ARABIC_CONTROLNET_PATH={os.path.abspath(args.output_dir)}")


if __name__ == "__main__":
    main()
