"""
Image composition utilities for overlaying rendered text.

This module takes:
- A generated scene image.
- A transparent text image (from text_renderer).

And overlays the text onto the scene in a simple, deterministic way.
"""
from __future__ import annotations

from typing import Tuple, Literal

from PIL import Image

Position = Literal["center", "top", "bottom"]


def overlay_text_on_scene(
    scene_image: Image.Image,
    text_image: Image.Image,
    position: Position = "center",
    y_offset_fraction: float = 0.0,
) -> Image.Image:
    """
    Overlay the text image onto the scene image.

    Args:
        scene_image: Base PIL image generated by diffusion.
        text_image: Transparent RGBA image containing rendered text.
        position: Vertical alignment ("center", "top", "bottom").
        y_offset_fraction: Additional vertical offset as a fraction of scene height
                           (e.g. 0.2 moves text slightly upwards).

    Returns:
        New PIL Image with text overlaid.
    """
    if scene_image.mode != "RGBA":
        base = scene_image.convert("RGBA")
    else:
        base = scene_image.copy()

    txt = text_image
    if txt.mode != "RGBA":
        txt = txt.convert("RGBA")

    scene_w, scene_h = base.size
    text_w, text_h = txt.size

    # Horizontal centre.
    x = (scene_w - text_w) // 2

    # Vertical position.
    if position == "top":
        y = int(scene_h * 0.15)
    elif position == "bottom":
        y = int(scene_h * 0.75 - text_h)
    else:  # "center"
        y = (scene_h - text_h) // 2

    # Apply additional offset.
    if y_offset_fraction != 0.0:
        y += int(scene_h * y_offset_fraction)

    # Clamp to valid region.
    x = max(0, min(x, scene_w - text_w))
    y = max(0, min(y, scene_h - text_h))

    base.alpha_composite(txt, dest=(x, y))
    return base


__all__ = ["overlay_text_on_scene"]

